apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: izocw70mz-go 
  janus-idp.io/tekton: izocw70mz-go
  backstage.io/kubernetes-id: izocw70mz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: izocw70mz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  