apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: izocw70mz-go
  janus-idp.io/tekton: izocw70mz-go
  backstage.io/kubernetes-id: izocw70mz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: izocw70mz-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
